#!/bin/sh

# This is a sample DAEMON file which is started at boottime. iIt must be names
# "start" here and will be renamed according to your Pluginname during
# installation. CAUTION! MAKE SURE YOUR SCRIPT EXITS CLEANLY! It is a good idea
# to start your daemon as background process. If you do something wrong here
# your user's systems may hang forever during boottime!

# Will be executed as user "root".

# Name this file "daemon.sh" in your plugin-archive. It will be renamed to NAME
# during installation

pluginname=$(basename $0 .sh)

if [ -x /usr/bin/logger ]
then
    /usr/bin/logger -s "loxberry-plugin-$pluginname - DAEMON Script from SMS Gateway Plugin"
fi

cp /opt/loxberry/data/plugins/$pluginname/supervisor.conf /etc/supervisor/conf.d/smsgateway.conf
cp /opt/loxberry/data/plugins/$pluginname/supervisorsend.conf /etc/supervisor/conf.d/smsgatewaysend.conf
cp /opt/loxberry/data/plugins/$pluginname/smsd.conf /etc/smsd.conf

# Normally we would "enable" once, but there seems to be no script with root permissions in loxberry structure
# apart from daemon startup
service supervisor start
/etc/init.d/smstools start

# supervisorctl start smsgateway

exit 0
